export const GET_USER = "GET_USER"
export const GET_POST = "GET_POST"
export const GET_COMMENT = "GET_COMMENT"
export const GET_TODO = "GET_TODO"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_PRODUCT = "GET_PRODUCT"
